# Any field left empty in this file will be automatically
# overridden by environment variables (.env) if provided.
#
# Priority:
# 1. Environment variables (highest priority)
# 2. YAML values
#
# Example:
#   database:
#     host: ""   # will be taken from DATABASE_HOST
#
# Make sure corresponding ENV variables are defined.
# =========================

global:
  env: prod

database:
  host:       # ENV: DATABASE_HOST
  port:       # ENV: DATABASE_PORT
  username:   # ENV: DATABASE_USER
  password:   # ENV: DATABASE_PASSWORD
  name:       # ENV: DATABASE_NAME
  sslmode:    # ENV: DATABASE_SSLMODE (optional)

stacks:
  rpc_url: "https://api.testnet.hiro.so"   # ENV: STACKS_RPC_URL
  contract: "ST6BVG3ADY71WYYTZKFNYXCE5604JX3KG7N7R17X.capebridge-test-v1"  # ENV: STACKS_CONTRACT
  signer_url: ""   # ENV: STACKS_SIGNER_URL
  bridge_token_trait: "ST1PQHQKV0RJXZFY1DGX8MNSNYVE3VGZJSRTPGZGM.usdcx"

base:
  rpc_url: "wss://ethereum-sepolia-rpc.publicnode.com"  # ENV: BASE_RPC_URL
  relayer_pk: ""   # ENV: BASE_RELAYER_PK
  contract: "0x7e3Bd761F1E1755274646e5CA48875fF44837533"  # ENV: BASE_CONTRACT
  chan_id: "11155111"
  start_block: 10457270
  federation_sync_address: "0x1a9B8ADB3BaC4038CCE91abE6E453B8CB8363b48"

relayer:
  node_id: "default"   # ENV: NODE_ID