services:
  bridge-api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: bridge-api-sse
    environment:
      - DATABASE_URL=postgres://${DATABASE_USER}:${DATABASE_PASSWORD}@postgres-1:5432/${DATABASE_NAME}?sslmode=enabled
      - PORT=8080
    ports:
      - "8080:8080"
    networks:
      - bridge-network
    restart: always

  bridge-frontend:
    build:
      context: ./bridge_nextjs
      dockerfile: Dockerfile
      args:
        - NEXT_PUBLIC_BRIDGE_API=https://capebridge.tech/api 
        - NEXT_PUBLIC_BRIDGE_CONTRACT=${BASE_BRIDGE_CONTRACT}
        - NEXT_PUBLIC_USDC_CONTRACT=${USDC_CONTRACT}
        - NEXT_PUBLIC_STACKS_NETWORK=${STACKS_NETWORK}
        - NEXT_PUBLIC_SUSDCX_CONTRACT=${SUSDCX_CONTRACT}
        - NEXT_PUBLIC_STACKS_BRIDGE_CONTRACT=${STACKS_BRIDGE_CONTRACT}
    container_name: bridge-nextjs-ui
    environment:
        - NEXT_PUBLIC_BRIDGE_API=https://capebridge.tech/api 
    ports:
      - "3000:3000"
    networks:
      - bridge-network
    depends_on:
      - bridge-api


networks:
  bridge-network:
    external: true
    name: bridge-network